# Generated by Django 2.0.6 on 2020-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'unknown')], default=1)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'tb_employee',
            },
        ),
    ]
