# Generated by Django 2.0.6 on 2020-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
